import type { MockStory } from "@/types";

export const MOCK_STORIES: MockStory[] = [
  {
    id: "story-001",
    title: "Tesla Recalls 2.4M Vehicles Over Autopilot Safety Concerns",
    status: "active",
    risk_level: "critical",
    created_at: "2024-12-10T08:00:00Z",
    updated_at: "2024-12-10T16:30:00Z",
    article_count: 47,
    sentiment_label: "negative",
    sentiment_score: -0.78,
    primary_article: {
      id: "art-001",
      headline: "Tesla Issues Massive Recall for Autopilot System After Fatal Accidents",
      hero_image_url: "https://picsum.photos/seed/tesla/1200/600",
      publisher: "Reuters",
      published_at: "2024-12-10T09:15:00Z",
      url: "https://reuters.com/business/autos/tesla-recall",
      sentiment_label: "negative",
      sentiment_score: -0.82,
      language: "en",
    },
    entities: [
      { id: "ent-001", canonical_name: "Tesla, Inc.", type: "company" },
      { id: "ent-002", canonical_name: "Elon Musk", type: "person" },
      { id: "ent-003", canonical_name: "NHTSA", type: "company" },
    ],
    insight: {
      id: "ins-001",
      what_happened:
        "Tesla has issued a recall affecting 2.4 million vehicles in the United States following a NHTSA investigation into autopilot-related accidents. The recall covers Model S, Model X, Model 3, and Model Y vehicles manufactured between 2015 and 2023. NHTSA found that the Autopilot system may allow drivers to disengage from active supervision more easily than permitted under federal safety standards.",
      why_happened:
        "The recall follows a two-year investigation triggered by 13 reported fatalities and dozens of serious injuries linked to Autopilot engagement. NHTSA determined that visual and audio alerts were insufficient to maintain driver attention. Tesla has agreed to push an over-the-air software update that adds additional safeguards, marking the first time a software update has been used to resolve an Autopilot safety recall at this scale.",
      generated_at: "2024-12-10T10:00:00Z",
      model_used: "claude-sonnet-3-5",
    },
    cluster_articles: [
      {
        id: "art-002",
        headline: "NHTSA Opens Investigation into Tesla Autopilot After Highway Death",
        publisher: "Bloomberg",
        published_at: "2024-12-08T14:00:00Z",
        url: "https://bloomberg.com/tesla-nhtsa",
        sentiment_label: "negative",
        sentiment_score: -0.71,
        hero_image_url: null,
        language: "en",
      },
      {
        id: "art-003",
        headline: "Tesla Stock Falls 8% on Recall Announcement",
        publisher: "Financial Times",
        published_at: "2024-12-10T11:30:00Z",
        url: "https://ft.com/tesla-stock",
        sentiment_label: "negative",
        sentiment_score: -0.65,
        hero_image_url: null,
        language: "en",
      },
      {
        id: "art-004",
        headline: "Families of Autopilot Victims React to Tesla Recall Decision",
        publisher: "New York Times",
        published_at: "2024-12-10T15:00:00Z",
        url: "https://nytimes.com/tesla-recall-families",
        sentiment_label: "negative",
        sentiment_score: -0.89,
        hero_image_url: null,
        language: "en",
      },
    ],
    timeline_events: [
      { at: "2022-06-01T00:00:00Z", label: "Investigation Opens", description: "NHTSA opens Autopilot safety investigation following 12 crashes." },
      { at: "2024-11-15T00:00:00Z", label: "Preliminary Findings", description: "NHTSA issues preliminary findings citing inadequate driver attention alerts." },
      { at: "2024-12-10T09:00:00Z", label: "Recall Announced", description: "Tesla and NHTSA jointly announce 2.4M vehicle recall." },
    ],
    recommendations: [
      {
        id: "rec-001",
        recommendation_text: "Issue a proactive statement acknowledging the recall and emphasising Tesla's commitment to safety. Avoid defensive language about Autopilot capabilities.",
        audience: "pr",
        risk_level: "critical",
        confidence_score: 0.92,
        needs_human_review: false,
      },
      {
        id: "rec-002",
        recommendation_text: "Brief the board on potential Q4 earnings impact. Analyst consensus suggests a 3-5% revenue headwind from delayed purchases. Consider pre-announcing a safety milestone to offset negative sentiment.",
        audience: "exec",
        risk_level: "high",
        confidence_score: 0.71,
        needs_human_review: true,
      },
    ],
  },
  {
    id: "story-002",
    title: "OpenAI Board Crisis: Altman Reinstated After 72-Hour Drama",
    status: "resolved",
    risk_level: "high",
    created_at: "2024-11-17T22:00:00Z",
    updated_at: "2024-11-21T18:00:00Z",
    article_count: 312,
    sentiment_label: "mixed",
    sentiment_score: 0.12,
    primary_article: {
      id: "art-010",
      headline: "Sam Altman Returns as OpenAI CEO After Board Reversal",
      hero_image_url: "https://picsum.photos/seed/openai/1200/600",
      publisher: "The Verge",
      published_at: "2024-11-21T14:30:00Z",
      url: "https://theverge.com/openai-altman-returns",
      sentiment_label: "mixed",
      sentiment_score: 0.21,
      language: "en",
    },
    entities: [
      { id: "ent-010", canonical_name: "OpenAI", type: "company" },
      { id: "ent-011", canonical_name: "Sam Altman", type: "person" },
      { id: "ent-012", canonical_name: "Microsoft", type: "company" },
    ],
    insight: {
      id: "ins-002",
      what_happened:
        "OpenAI's board abruptly fired CEO Sam Altman on November 17, citing a lack of candour with the board. Within 48 hours, nearly all OpenAI employees signed a letter threatening to resign if Altman was not reinstated. Microsoft, OpenAI's largest investor, initially offered Altman a role leading a new AI lab. After intense negotiations, Altman was reinstated on November 21 with a restructured board.",
      why_happened:
        "The firing stemmed from a months-long tension between the safety-focused board faction led by Ilya Sutskever and the commercially-oriented leadership team around Altman. The board lacked the legal authority to prevent employee mass departure and had not secured a CEO replacement. Microsoft's threat to absorb OpenAI's talent accelerated the reversal. The crisis exposed fundamental governance weaknesses in OpenAI's non-profit/for-profit hybrid structure.",
      generated_at: "2024-11-21T16:00:00Z",
      model_used: "claude-sonnet-3-5",
    },
    cluster_articles: [
      {
        id: "art-011",
        headline: "OpenAI Board Fires Sam Altman as CEO",
        publisher: "Reuters",
        published_at: "2024-11-17T22:00:00Z",
        url: "https://reuters.com/openai-altman-fired",
        sentiment_label: "negative",
        sentiment_score: -0.61,
        hero_image_url: null,
        language: "en",
      },
      {
        id: "art-012",
        headline: "700 OpenAI Employees Threaten to Quit Unless Altman Reinstated",
        publisher: "Bloomberg",
        published_at: "2024-11-19T18:00:00Z",
        url: "https://bloomberg.com/openai-employee-letter",
        sentiment_label: "negative",
        sentiment_score: -0.45,
        hero_image_url: null,
        language: "en",
      },
    ],
    timeline_events: [
      { at: "2024-11-17T22:00:00Z", label: "Altman Fired", description: "Board removes Altman via surprise announcement." },
      { at: "2024-11-19T12:00:00Z", label: "Employee Letter", description: "700+ employees sign reinstatement ultimatum." },
      { at: "2024-11-21T14:30:00Z", label: "Altman Returns", description: "Altman reinstated; three board members replaced." },
    ],
    recommendations: [
      {
        id: "rec-010",
        recommendation_text: "The governance crisis creates a window to position your AI products as 'stable alternatives' to OpenAI. Issue a blog post on your AI governance principles without directly referencing OpenAI's instability.",
        audience: "marketing",
        risk_level: "medium",
        confidence_score: 0.67,
        needs_human_review: true,
      },
    ],
  },
  {
    id: "story-003",
    title: "Apple Vision Pro Sales Disappoint, Analysts Cut Forecasts",
    status: "active",
    risk_level: "medium",
    created_at: "2024-12-05T10:00:00Z",
    updated_at: "2024-12-09T12:00:00Z",
    article_count: 89,
    sentiment_label: "negative",
    sentiment_score: -0.44,
    primary_article: {
      id: "art-020",
      headline: "Apple Vision Pro Sells Below Expectations in First Year",
      hero_image_url: "https://picsum.photos/seed/apple/1200/600",
      publisher: "WSJ",
      published_at: "2024-12-05T11:00:00Z",
      url: "https://wsj.com/apple-vision-pro-sales",
      sentiment_label: "negative",
      sentiment_score: -0.48,
      language: "en",
    },
    entities: [
      { id: "ent-020", canonical_name: "Apple Inc.", type: "company" },
      { id: "ent-021", canonical_name: "Tim Cook", type: "person" },
    ],
    insight: {
      id: "ins-003",
      what_happened:
        "Apple's Vision Pro spatial computing headset has sold approximately 400,000 units in its first eight months on the market — significantly below the 1 million unit target analysts had set for year one. Multiple suppliers have reportedly reduced order forecasts, and some early adopters have returned their devices citing weight, comfort, and limited app ecosystem.",
      why_happened:
        "The Vision Pro's $3,499 price point has proven a significant barrier for mainstream adoption in a challenging consumer hardware environment. The device targets enterprise use cases, but enterprise sales cycles are long and require dedicated app development investment that most companies haven't made yet. The headset weight issue (650g) was a known hardware constraint but has proven more significant to user retention than Apple anticipated.",
      generated_at: "2024-12-05T12:00:00Z",
      model_used: "claude-haiku-3-5",
    },
    cluster_articles: [
      {
        id: "art-021",
        headline: "Apple Cuts Vision Pro Orders Amid Slow Sales",
        publisher: "Bloomberg",
        published_at: "2024-12-03T09:00:00Z",
        url: "https://bloomberg.com/apple-vision-pro-cuts",
        sentiment_label: "negative",
        sentiment_score: -0.55,
        hero_image_url: null,
        language: "en",
      },
      {
        id: "art-022",
        headline: "Developers Pull Vision Pro Apps as User Numbers Stagnate",
        publisher: "9to5Mac",
        published_at: "2024-12-07T15:00:00Z",
        url: "https://9to5mac.com/vision-pro-apps",
        sentiment_label: "negative",
        sentiment_score: -0.39,
        hero_image_url: null,
        language: "en",
      },
    ],
    timeline_events: [
      { at: "2024-02-02T00:00:00Z", label: "Vision Pro Launches", description: "Apple releases Vision Pro at $3,499." },
      { at: "2024-08-01T00:00:00Z", label: "Sales Slow", description: "Reports emerge of slowing sell-through rates." },
      { at: "2024-12-05T00:00:00Z", label: "Analyst Downgrades", description: "Multiple analysts cut Apple price targets citing Vision Pro miss." },
    ],
    recommendations: [
      {
        id: "rec-020",
        recommendation_text: "Competitors in AR/VR should accelerate developer outreach programs — Apple's ecosystem vacuum creates a rare six-month window to attract cross-platform development resources.",
        audience: "marketing",
        risk_level: "medium",
        confidence_score: 0.81,
        needs_human_review: false,
      },
    ],
  },
  {
    id: "story-004",
    title: "NVIDIA Becomes Most Valuable Company Surpassing Microsoft",
    status: "active",
    risk_level: "low",
    created_at: "2024-06-18T14:00:00Z",
    updated_at: "2024-06-20T10:00:00Z",
    article_count: 198,
    sentiment_label: "positive",
    sentiment_score: 0.87,
    primary_article: {
      id: "art-030",
      headline: "NVIDIA Hits $3.3 Trillion Valuation, Surpasses Microsoft",
      hero_image_url: "https://picsum.photos/seed/nvidia/1200/600",
      publisher: "Bloomberg",
      published_at: "2024-06-18T15:00:00Z",
      url: "https://bloomberg.com/nvidia-most-valuable",
      sentiment_label: "positive",
      sentiment_score: 0.91,
      language: "en",
    },
    entities: [
      { id: "ent-030", canonical_name: "NVIDIA Corporation", type: "company" },
      { id: "ent-031", canonical_name: "Jensen Huang", type: "person" },
    ],
    insight: {
      id: "ins-004",
      what_happened:
        "NVIDIA briefly became the world's most valuable publicly traded company on June 18, 2024, surpassing Microsoft with a market capitalisation of $3.34 trillion. The milestone follows a 200% gain in NVIDIA's stock price over the preceding 12 months, driven almost entirely by demand for its H100 and upcoming B100 GPU chips from hyperscalers building AI infrastructure.",
      why_happened:
        "The AI infrastructure buildout has concentrated unprecedented demand on NVIDIA's GPU architecture. CUDA's decade-long software moat means switching costs for existing AI workloads are extremely high. Microsoft, Google, Amazon, and Meta collectively spent over $200 billion on AI infrastructure in 2024, the majority using NVIDIA hardware. Jensen Huang's strategic bet on CUDA as a software platform — made in 2007 — is the fundamental reason NVIDIA captured this market rather than AMD or Intel.",
      generated_at: "2024-06-18T16:00:00Z",
      model_used: "claude-sonnet-3-5",
    },
    cluster_articles: [
      {
        id: "art-031",
        headline: "NVIDIA Q1 Revenue Surges 262% Year-Over-Year",
        publisher: "Reuters",
        published_at: "2024-05-22T20:00:00Z",
        url: "https://reuters.com/nvidia-q1",
        sentiment_label: "positive",
        sentiment_score: 0.88,
        hero_image_url: null,
        language: "en",
      },
    ],
    timeline_events: [
      { at: "2024-01-01T00:00:00Z", label: "Year Begins", description: "NVIDIA at $1.2T market cap, third behind Apple and Microsoft." },
      { at: "2024-05-22T00:00:00Z", label: "Blowout Earnings", description: "Q1 revenue $26B, up 262% YoY. Stock surges 9%." },
      { at: "2024-06-18T00:00:00Z", label: "Valuation Peak", description: "NVIDIA reaches $3.34T, becomes most valuable company." },
    ],
    recommendations: [
      {
        id: "rec-030",
        recommendation_text: "If your organisation uses NVIDIA hardware for AI workloads, this is a strategic moment to evaluate long-term supply agreements. Demand will outstrip supply through 2025.",
        audience: "exec",
        risk_level: "low",
        confidence_score: 0.88,
        needs_human_review: false,
      },
    ],
  },
  {
    id: "story-005",
    title: "Meta Announces 11,000 Layoffs in Second Major Round of Cuts",
    status: "resolved",
    risk_level: "medium",
    created_at: "2024-11-09T09:00:00Z",
    updated_at: "2024-11-15T17:00:00Z",
    article_count: 156,
    sentiment_label: "negative",
    sentiment_score: -0.52,
    primary_article: {
      id: "art-040",
      headline: "Meta Cuts 11,000 Jobs as Zuckerberg Declares Year of Efficiency",
      hero_image_url: "https://picsum.photos/seed/meta/1200/600",
      publisher: "Financial Times",
      published_at: "2024-11-09T10:00:00Z",
      url: "https://ft.com/meta-layoffs",
      sentiment_label: "negative",
      sentiment_score: -0.58,
      language: "en",
    },
    entities: [
      { id: "ent-040", canonical_name: "Meta Platforms", type: "company" },
      { id: "ent-041", canonical_name: "Mark Zuckerberg", type: "person" },
    ],
    insight: {
      id: "ins-005",
      what_happened:
        "Meta Platforms announced the termination of 11,000 employees — approximately 13% of its workforce — as part of a broader restructuring effort Mark Zuckerberg called the 'Year of Efficiency.' The cuts primarily affected recruiting, reality labs, and middle management layers. The announcement came one week after Meta reported third-quarter ad revenue that missed analyst estimates.",
      why_happened:
        "Meta over-hired by over 20,000 people during the 2020-2022 pandemic boom, a period when digital advertising grew at unsustainable rates. The reversal in digital ad spending in 2023, combined with Apple's iOS privacy changes reducing ad targeting precision, created severe margin pressure. Zuckerberg faced activist investor pressure from multiple funds to demonstrate cost discipline. The layoffs are also designed to fund the ongoing metaverse investment without returning negative cash flow.",
      generated_at: "2024-11-09T11:00:00Z",
      model_used: "claude-haiku-3-5",
    },
    cluster_articles: [
      {
        id: "art-041",
        headline: "Meta Stock Rises 5% on Layoff Announcement",
        publisher: "WSJ",
        published_at: "2024-11-09T14:00:00Z",
        url: "https://wsj.com/meta-stock",
        sentiment_label: "positive",
        sentiment_score: 0.41,
        hero_image_url: null,
        language: "en",
      },
    ],
    timeline_events: [
      { at: "2024-11-09T09:00:00Z", label: "Announcement", description: "Zuckerberg emails staff announcing 11,000 job cuts." },
      { at: "2024-11-09T13:00:00Z", label: "Market Reaction", description: "META stock rises 5% as investors cheer cost discipline." },
    ],
    recommendations: [
      {
        id: "rec-040",
        recommendation_text: "This is a talent acquisition opportunity. Former Meta engineers with AI and ML experience will enter the market over the next 30 days. Activate recruiting pipelines immediately for ML infrastructure roles.",
        audience: "exec",
        risk_level: "low",
        confidence_score: 0.94,
        needs_human_review: false,
      },
    ],
  },
  {
    id: "story-006",
    title: "Boeing Whistleblower Found Dead Ahead of Senate Testimony",
    status: "active",
    risk_level: "critical",
    created_at: "2024-03-13T14:00:00Z",
    updated_at: "2024-03-15T10:00:00Z",
    article_count: 234,
    sentiment_label: "negative",
    sentiment_score: -0.93,
    primary_article: {
      id: "art-050",
      headline: "Boeing Quality Whistleblower Found Dead Days Before Congressional Testimony",
      hero_image_url: "https://picsum.photos/seed/boeing/1200/600",
      publisher: "BBC News",
      published_at: "2024-03-13T15:00:00Z",
      url: "https://bbc.com/boeing-whistleblower",
      sentiment_label: "negative",
      sentiment_score: -0.95,
      language: "en",
    },
    entities: [
      { id: "ent-050", canonical_name: "Boeing", type: "company" },
      { id: "ent-051", canonical_name: "FAA", type: "company" },
    ],
    insight: {
      id: "ins-006",
      what_happened:
        "John Barnett, a Boeing quality control inspector who had filed whistleblower complaints about manufacturing defects in the 787 Dreamliner, was found dead in his car on March 9, 2024 — during a break in his deposition as part of his lawsuit against Boeing. Local authorities have classified the death as an apparent self-inflicted gunshot wound. The death has intensified Congressional scrutiny of Boeing and the FAA's oversight role.",
      why_happened:
        "Barnett's death follows years of escalating tension between Boeing's quality control staff and management, stemming from production pressure that allegedly led to shortcuts in the 787 fuselage assembly process. His 2019 whistleblower complaint alleged that defective parts were being deliberately concealed in aircraft assemblies. The timing — during active deposition testimony — has prompted calls for an independent investigation and added to a crisis period that already included the Alaska Airlines 737 MAX 9 door plug incident in January 2024.",
      generated_at: "2024-03-13T17:00:00Z",
      model_used: "claude-sonnet-3-5",
    },
    cluster_articles: [
      {
        id: "art-051",
        headline: "Alaska Airlines 737 MAX Door Plug Blows Out Mid-Flight",
        publisher: "Reuters",
        published_at: "2024-01-05T09:00:00Z",
        url: "https://reuters.com/alaska-boeing",
        sentiment_label: "negative",
        sentiment_score: -0.91,
        hero_image_url: null,
        language: "en",
      },
    ],
    timeline_events: [
      { at: "2024-01-05T00:00:00Z", label: "Door Plug Incident", description: "Alaska Airlines 737 MAX 9 loses door plug at 16,000ft." },
      { at: "2024-03-09T00:00:00Z", label: "Whistleblower Dies", description: "John Barnett found dead during deposition break." },
      { at: "2024-03-13T00:00:00Z", label: "Congressional Hearing", description: "Senate Commerce Committee announces emergency Boeing hearing." },
    ],
    recommendations: [
      {
        id: "rec-050",
        recommendation_text: "Avoid any public commentary on Boeing that could be perceived as speculative about the whistleblower case. Monitor aviation safety social channels for any spillover to competitor aircraft models.",
        audience: "pr",
        risk_level: "critical",
        confidence_score: 0.96,
        needs_human_review: false,
      },
    ],
  },
  {
    id: "story-007",
    title: "Google Found Guilty of Illegal Monopoly in Search, DOJ Seeks Break-Up",
    status: "active",
    risk_level: "high",
    created_at: "2024-08-05T16:00:00Z",
    updated_at: "2024-08-07T09:00:00Z",
    article_count: 276,
    sentiment_label: "negative",
    sentiment_score: -0.61,
    primary_article: {
      id: "art-060",
      headline: "Judge Rules Google Illegally Monopolised Search Market",
      hero_image_url: "https://picsum.photos/seed/google/1200/600",
      publisher: "New York Times",
      published_at: "2024-08-05T17:00:00Z",
      url: "https://nytimes.com/google-antitrust",
      sentiment_label: "negative",
      sentiment_score: -0.67,
      language: "en",
    },
    entities: [
      { id: "ent-060", canonical_name: "Alphabet Inc.", type: "company" },
      { id: "ent-061", canonical_name: "US Department of Justice", type: "company" },
      { id: "ent-062", canonical_name: "Sundar Pichai", type: "person" },
    ],
    insight: {
      id: "ins-007",
      what_happened:
        "US District Judge Amit Mehta ruled on August 5, 2024 that Google had illegally monopolised the general search and search advertising markets in violation of the Sherman Antitrust Act. The ruling found that Google's exclusive default agreements with device manufacturers — including Apple ($18B/year) and Android OEMs — illegally foreclosed competition. A separate remedies trial is scheduled to determine whether the DOJ's proposed structural remedies, including potentially forcing Google to divest Chrome or Android, should be implemented.",
      why_happened:
        "The ruling centres on Google paying billions annually to be the default search engine on devices, which the court found created a self-reinforcing feedback loop: more queries → better AI training data → better results → higher willingness to pay for defaults → less chance for competitors to gain scale. The DOJ argued this created a structural competitive barrier that even a technically superior competitor could not overcome. Google argued the payments represented legitimate competition on the merits.",
      generated_at: "2024-08-05T18:00:00Z",
      model_used: "claude-sonnet-3-5",
    },
    cluster_articles: [
      {
        id: "art-061",
        headline: "DOJ Proposes Breaking Up Google, Forcing Sale of Chrome",
        publisher: "Bloomberg",
        published_at: "2024-11-20T14:00:00Z",
        url: "https://bloomberg.com/doj-google-breakup",
        sentiment_label: "negative",
        sentiment_score: -0.72,
        hero_image_url: null,
        language: "en",
      },
    ],
    timeline_events: [
      { at: "2023-09-12T00:00:00Z", label: "Trial Begins", description: "DOJ antitrust trial against Google opens in DC." },
      { at: "2024-08-05T00:00:00Z", label: "Guilty Ruling", description: "Judge Mehta finds Google guilty of illegal monopoly." },
      { at: "2024-11-20T00:00:00Z", label: "Remedies Proposed", description: "DOJ files proposed remedies including Chrome divestiture." },
    ],
    recommendations: [
      {
        id: "rec-060",
        recommendation_text: "The ruling and potential Google restructuring creates the largest search distribution opportunity in 20 years. Evaluate default search placement bids for device categories where Google's contracts may be enjoined pending remedies.",
        audience: "exec",
        risk_level: "high",
        confidence_score: 0.77,
        needs_human_review: true,
      },
      {
        id: "rec-061",
        recommendation_text: "Review all advertising spend allocated to Google Search. Diversify into Bing/Copilot and emerging AI-powered search channels over the next two quarters as default placements shift.",
        audience: "marketing",
        risk_level: "medium",
        confidence_score: 0.85,
        needs_human_review: false,
      },
    ],
  },
  {
    id: "story-008",
    title: "Anthropic Raises $4B from Amazon in Strategic AI Partnership",
    status: "active",
    risk_level: "low",
    created_at: "2024-03-27T13:00:00Z",
    updated_at: "2024-03-28T08:00:00Z",
    article_count: 91,
    sentiment_label: "positive",
    sentiment_score: 0.76,
    primary_article: {
      id: "art-070",
      headline: "Amazon Completes $4B Investment in Anthropic, Cementing AWS-Claude Partnership",
      hero_image_url: "https://picsum.photos/seed/anthropic/1200/600",
      publisher: "Reuters",
      published_at: "2024-03-27T14:00:00Z",
      url: "https://reuters.com/anthropic-amazon",
      sentiment_label: "positive",
      sentiment_score: 0.79,
      language: "en",
    },
    entities: [
      { id: "ent-070", canonical_name: "Anthropic", type: "company" },
      { id: "ent-071", canonical_name: "Amazon", type: "company" },
      { id: "ent-072", canonical_name: "Dario Amodei", type: "person" },
    ],
    insight: {
      id: "ins-008",
      what_happened:
        "Amazon Web Services completed its $4 billion investment in Anthropic, the AI safety company behind the Claude model family. The deal makes Anthropic the first AI company to receive investments totaling over $7 billion from two of the world's largest cloud providers simultaneously (Google invested $300M in early 2023). Anthropic will use AWS Trainium and Inferentia chips as its primary training infrastructure, and Claude will be deeply integrated into Amazon Bedrock.",
      why_happened:
        "Amazon's investment is a strategic counter to Microsoft's $13B stake in OpenAI. With Claude-class models now competitive with GPT-4 on many benchmarks, AWS needed a premier AI partner to compete with Azure's OpenAI integration. For Anthropic, the compute access is existential — training frontier models requires hundreds of millions in GPU hours, and AWS gives them access at scale without the market concentration risk of relying entirely on NVIDIA's spot market.",
      generated_at: "2024-03-27T15:00:00Z",
      model_used: "claude-haiku-3-5",
    },
    cluster_articles: [
      {
        id: "art-071",
        headline: "Google Invests Additional $2B in Anthropic",
        publisher: "Bloomberg",
        published_at: "2023-10-27T10:00:00Z",
        url: "https://bloomberg.com/google-anthropic",
        sentiment_label: "positive",
        sentiment_score: 0.71,
        hero_image_url: null,
        language: "en",
      },
    ],
    timeline_events: [
      { at: "2023-02-01T00:00:00Z", label: "Anthropic Founded", description: "Former OpenAI team launches Anthropic with safety focus." },
      { at: "2023-10-27T00:00:00Z", label: "Google Invests", description: "Google commits up to $2B to Anthropic." },
      { at: "2024-03-27T00:00:00Z", label: "Amazon Closes", description: "Amazon's $4B investment in Anthropic closes." },
    ],
    recommendations: [
      {
        id: "rec-070",
        recommendation_text: "Evaluate Claude API via Amazon Bedrock for production AI workloads — the AWS integration simplifies compliance and billing consolidation for enterprises already on AWS.",
        audience: "exec",
        risk_level: "low",
        confidence_score: 0.91,
        needs_human_review: false,
      },
    ],
  },
];
