"""add is_duplicate_of back

Revision ID: 4af60d653b05
Revises: da170b798b9c
Create Date: 2026-08-03 14:48:36.489236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af60d653b05'
down_revision: Union[str, Sequence[str], None] = 'da170b798b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_duplicate_of', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_articles_is_duplicate_of'), 'articles', ['is_duplicate_of'], unique=False)
    op.create_foreign_key(None, 'articles', 'articles', ['is_duplicate_of'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_is_duplicate_of'), table_name='articles')
    op.drop_column('articles', 'is_duplicate_of')
    # ### end Alembic commands ###
