"""Add watchlist_entities table

Revision ID: 511cf88a1519
Revises: 912eaf7245a9
Create Date: 2026-08-03 10:40:15.465282

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '511cf88a1519'
down_revision: str | Sequence[str] | None = '912eaf7245a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
