"""add agent_mode and reasoning_trace to recommendations

Revision ID: 6006cd2090d9
Revises: 4af60d653b05
Create Date: 2026-08-03 15:41:07.287466

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6006cd2090d9'
down_revision: str | Sequence[str] | None = '4af60d653b05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_recommendations', sa.Column('agent_mode', sa.String(length=20), server_default=sa.text("text('''fast_path''')"), nullable=False))
    op.add_column('story_recommendations', sa.Column('reasoning_trace', sa.Text(), server_default=sa.text("text('''[]''')"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_recommendations', 'reasoning_trace')
    op.drop_column('story_recommendations', 'agent_mode')
    # ### end Alembic commands ###
