"""Add agentic brief fields

Revision ID: 912eaf7245a9
Revises: 0007
Create Date: 2026-07-22 11:51:54.254899

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '912eaf7245a9'
down_revision: str | Sequence[str] | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_log_story_id'), table_name='llm_usage_log')
    op.drop_table('llm_usage_log')
    op.drop_index(op.f('ix_alerts_watchlist_feedback'), table_name='alerts', postgresql_where='(user_feedback IS NOT NULL)')
    op.drop_index(op.f('ix_articles_agentic_dedup'), table_name='articles', postgresql_where="((dedup_agent_path)::text <> 'fast_path'::text)")
    op.drop_index(op.f('ix_articles_content_tsv'), table_name='articles', postgresql_using='gin')
    op.drop_index(op.f('ix_articles_is_duplicate_of'), table_name='articles')
    op.drop_constraint(op.f('articles_is_duplicate_of_fkey'), 'articles', type_='foreignkey')
    op.drop_column('articles', 'is_duplicate_of')
    op.alter_column('entities', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('ix_entity_aliases_lower_alias'), table_name='entity_aliases')
    op.alter_column('sources', 'config_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.add_column('stories', sa.Column('is_pattern', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_index(op.f('ix_stories_entity_status_updated'), table_name='stories', postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('ix_stories_status_updated_partial'), table_name='stories', postgresql_where="((status)::text = 'active'::text)")
    op.drop_index(op.f('ix_story_articles_story_article'), table_name='story_articles')
    op.add_column('story_insights', sa.Column('reasoning_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_story_recs_story_id'), table_name='story_recommendations')
    op.create_index(op.f('ix_story_recommendations_story_id'), 'story_recommendations', ['story_id'], unique=False)
    op.drop_column('story_recommendations', 'agent_mode')
    op.drop_column('story_recommendations', 'reasoning_trace')
    op.alter_column('watchlists', 'alert_channels_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlists', 'alert_channels_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.add_column('story_recommendations', sa.Column('reasoning_trace', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('story_recommendations', sa.Column('agent_mode', sa.VARCHAR(length=20), server_default=sa.text("'single_shot'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_story_recommendations_story_id'), table_name='story_recommendations')
    op.create_index(op.f('ix_story_recs_story_id'), 'story_recommendations', ['story_id'], unique=False)
    op.drop_column('story_insights', 'reasoning_trace')
    op.create_index(op.f('ix_story_articles_story_article'), 'story_articles', ['story_id', 'article_id'], unique=False)
    op.create_index(op.f('ix_stories_status_updated_partial'), 'stories', [sa.literal_column('updated_at DESC')], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.create_index(op.f('ix_stories_entity_status_updated'), 'stories', ['primary_entity_id', 'status', sa.literal_column('updated_at DESC')], unique=False, postgresql_where="((status)::text = 'active'::text)")
    op.drop_column('stories', 'is_pattern')
    op.alter_column('sources', 'config_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index(op.f('ix_entity_aliases_lower_alias'), 'entity_aliases', [sa.literal_column('lower(alias_text::text)')], unique=False)
    op.alter_column('entities', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.add_column('articles', sa.Column('is_duplicate_of', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('articles_is_duplicate_of_fkey'), 'articles', 'articles', ['is_duplicate_of'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_articles_is_duplicate_of'), 'articles', ['is_duplicate_of'], unique=False)
    op.create_index(op.f('ix_articles_content_tsv'), 'articles', [sa.literal_column("to_tsvector('english'::regconfig, COALESCE(clean_content, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_articles_agentic_dedup'), 'articles', ['dedup_agent_path'], unique=False, postgresql_where="((dedup_agent_path)::text <> 'fast_path'::text)")
    op.create_index(op.f('ix_alerts_watchlist_feedback'), 'alerts', ['watchlist_id', 'user_feedback'], unique=False, postgresql_where='(user_feedback IS NOT NULL)')
    op.create_table('llm_usage_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('story_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cost_usd_micro', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Approximate cost in millionths of USD (micro-USD)'),
    sa.Column('latency_ms', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('llm_usage_log_story_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_usage_log_pkey'))
    )
    op.create_index(op.f('ix_llm_usage_log_story_id'), 'llm_usage_log', ['story_id'], unique=False)
    # ### end Alembic commands ###
