"""Add missing is_duplicate_of column

Revision ID: da170b798b9c
Revises: 511cf88a1519
Create Date: 2026-08-03 10:51:23.335156

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'da170b798b9c'
down_revision: str | Sequence[str] | None = '511cf88a1519'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
